import type { CapacitorConfig } from '@capacitor/cli'

// Capacitor configuration for the Volt Android shell.
//
// This is a Node-side config file (not part of the Svelte/Vite app bundle),
// so it is type-checked via tsconfig.node.json rather than svelte-check.
//
// The Android app reuses the exact Svelte frontend inside a Capacitor WebView
// shell (see design.md "Resolving the Android Open Technical Decision"). The
// native project is generated by `npx cap add android` in a properly
// provisioned environment (Java + Android SDK); see scripts/set-android-version.mjs
// and tasks 22.2 / 22.4 for the gomobile bridge and release wiring.
//
// Version injection (Requirement 15.9): the Android Semantic_Version lives in
// the generated android/app/build.gradle (`versionName` / `versionCode`). The
// release workflow (task 22.4) runs `npm run android:set-version <semver>`
// before building, which rewrites those fields from the pushed git tag. The
// in-app About/Settings view reads the running version through the Capacitor
// backend's appVersion() once the native bridge lands in task 22.2.
const config: CapacitorConfig = {
  // Reverse-domain application id used as the Android package id.
  appId: 'dev.volt.apiclient',
  // Display name shown under the launcher icon. Matches the desktop product name.
  appName: 'Volt',
  // The Vite build output directory that Capacitor copies into the WebView on
  // `cap sync`. `npm run build` writes the Svelte/Vite bundle here, so the
  // Android shell hosts the same design system and narrow-viewport responsive
  // layout as the desktop app (Requirement 15.6) without any separate UI build.
  webDir: 'dist',
  android: {
    // Serve the bundled assets over https://, which keeps a secure origin for
    // the WebView and matches how a packaged (non-live-reload) app should run.
    // No `server.url` is set, so assets are loaded from the bundled webDir
    // rather than a remote server.
    allowMixedContent: false,
  },
  server: {
    androidScheme: 'https',
  },
}

export default config
