// wailsBackend forwards every Backend call to the Go App bindings that Wails
// exposes on the window at runtime as window.go.main.App.<Method>. We call
// through that runtime accessor rather than importing the generated
// ../../wailsjs/go/main/App module, because those generated files are
// regenerated by `wails generate`/`wails build` and can be stale against the
// current Go API between builds. The runtime accessor is always current with
// the compiled binary.

import type { Backend } from './index'
import type {
  Collection,
  Environment,
  Folder,
  HTTPResponse,
  HistoryEntry,
  ImportResult,
  RawRequest,
  SavedRequest,
  Settings,
} from '../models'

/**
 * The shape of the App binding object Wails injects at window.go.main.App.
 * Each bound Go method becomes an async function returning a Promise. Go
 * methods that return only an error resolve to void in JS; methods returning
 * `[]byte` resolve to a base64-encoded string.
 */
interface WailsApp {
  ExecuteRequest(req: RawRequest): Promise<HTTPResponse>

  ListTree(): Promise<Collection[]>
  SaveCollection(c: Collection): Promise<Collection>
  RenameCollection(id: string, name: string): Promise<void>
  DeleteCollection(id: string): Promise<void>
  SaveFolder(f: Folder, parentId: string): Promise<Folder>
  DeleteFolder(id: string): Promise<void>
  SaveRequest(req: SavedRequest, parentId: string): Promise<SavedRequest>
  DeleteRequest(id: string): Promise<void>
  MoveRequest(requestId: string, targetParentId: string): Promise<void>

  ListEnvironments(): Promise<Environment[]>
  SaveEnvironment(e: Environment): Promise<Environment>
  DeleteEnvironment(id: string): Promise<void>
  SetActiveEnvironment(id: string): Promise<void>

  ListHistory(): Promise<HistoryEntry[]>
  ClearHistory(): Promise<void>
  MigrateLegacyHistory(entries: HistoryEntry[]): Promise<boolean>

  GetSettings(): Promise<Settings>
  SaveSettings(s: Settings): Promise<void>

  ExportCollection(id: string): Promise<string>
  ExportEnvironment(id: string): Promise<string>
  Import(data: string): Promise<ImportResult>

  AppVersion(): Promise<string>
}

interface WailsWindow {
  go?: { main?: { App?: WailsApp } }
}

/** Resolves the live Wails App bindings, throwing if the runtime is absent. */
function app(): WailsApp {
  const bound = (window as unknown as WailsWindow).go?.main?.App
  if (bound == null) {
    throw new Error('volt: Wails runtime bindings (window.go.main.App) are not available')
  }
  return bound
}

export const wailsBackend: Backend = {
  executeRequest: (req) => app().ExecuteRequest(req),

  listTree: () => app().ListTree(),
  saveCollection: (c) => app().SaveCollection(c),
  renameCollection: (id, name) => app().RenameCollection(id, name),
  deleteCollection: (id) => app().DeleteCollection(id),
  saveFolder: (f, parentId) => app().SaveFolder(f, parentId),
  deleteFolder: (id) => app().DeleteFolder(id),
  saveRequest: (req, parentId) => app().SaveRequest(req, parentId),
  deleteRequest: (id) => app().DeleteRequest(id),
  moveRequest: (requestId, targetParentId) => app().MoveRequest(requestId, targetParentId),

  listEnvironments: () => app().ListEnvironments(),
  saveEnvironment: (e) => app().SaveEnvironment(e),
  deleteEnvironment: (id) => app().DeleteEnvironment(id),
  setActiveEnvironment: (id) => app().SetActiveEnvironment(id),

  listHistory: () => app().ListHistory(),
  clearHistory: () => app().ClearHistory(),
  migrateLegacyHistory: (entries) => app().MigrateLegacyHistory(entries),

  getSettings: () => app().GetSettings(),
  saveSettings: (s) => app().SaveSettings(s),

  exportCollection: (id) => app().ExportCollection(id),
  exportEnvironment: (id) => app().ExportEnvironment(id),
  importData: (data) => app().Import(data),

  appVersion: () => app().AppVersion(),
}
