// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {store} from '../models';

export function AppVersion():Promise<string>;

export function ClearHistory():Promise<void>;

export function DeleteCollection(arg1:string):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function DeleteRequest(arg1:string):Promise<void>;

export function ExecuteRequest(arg1:model.RawRequest):Promise<model.HTTPResponse>;

export function ExportCollection(arg1:string):Promise<Array<number>>;

export function ExportEnvironment(arg1:string):Promise<Array<number>>;

export function GetSettings():Promise<model.Settings>;

export function Import(arg1:Array<number>):Promise<store.ImportResult>;

export function ListEnvironments():Promise<Array<model.Environment>>;

export function ListHistory():Promise<Array<model.HistoryEntry>>;

export function ListTree():Promise<Array<model.Collection>>;

export function MigrateLegacyHistory(arg1:Array<model.HistoryEntry>):Promise<boolean>;

export function MoveRequest(arg1:string,arg2:string):Promise<void>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SaveCollection(arg1:model.Collection):Promise<model.Collection>;

export function SaveEnvironment(arg1:model.Environment):Promise<model.Environment>;

export function SaveFolder(arg1:model.Folder,arg2:string):Promise<model.Folder>;

export function SaveRequest(arg1:model.SavedRequest,arg2:string):Promise<model.SavedRequest>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SetActiveEnvironment(arg1:string):Promise<void>;
