// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function ExecuteRequest(arg1) {
  return window['go']['main']['App']['ExecuteRequest'](arg1);
}

export function ExportCollection(arg1) {
  return window['go']['main']['App']['ExportCollection'](arg1);
}

export function ExportEnvironment(arg1) {
  return window['go']['main']['App']['ExportEnvironment'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Import(arg1) {
  return window['go']['main']['App']['Import'](arg1);
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function ListTree() {
  return window['go']['main']['App']['ListTree']();
}

export function MigrateLegacyHistory(arg1) {
  return window['go']['main']['App']['MigrateLegacyHistory'](arg1);
}

export function MoveRequest(arg1, arg2) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function SaveCollection(arg1) {
  return window['go']['main']['App']['SaveCollection'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveFolder(arg1, arg2) {
  return window['go']['main']['App']['SaveFolder'](arg1, arg2);
}

export function SaveRequest(arg1, arg2) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}
